site_name: My Docs| Sean Njela
site_description: Professional docs implementation.
site_url: https://sean-njela.github.io/docs/
site_author: Sean Njela
repo_url: https://github.com/sean-njela/docs/
repo_name: sean-njela/docs/
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 Sean Njela - Personal Portfolio Project

# Configuration
theme:
  name: material
  language: en
  # favicon: assets/images/argocd.png #must incomment if it exists
  # logo: assets/images/argocd.png #must incomment if it exists
  # icon:
  #   logo: logo
  # must uncomment when you replace the logo path
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search:
      lang: en
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mike:
      alias_type: redirect   # options: symlink (default), redirect, copy
      version_selector: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # ignore editor warning
      emoji_index: !!python/name:material.extensions.emoji.twemoji # ignore editor warning
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # ignore editor warning
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify # ignore editor warning
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sean-njela # replace with yours
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/sean-njela # replace with yours
  generator: false
  version:
    provider: mike
    alias: true
    default: latest
  status:
    new: Recently added
    deprecated: Deprecated

nav:
  - Home: index.md # NEVER NAME THIS ANYTHING ELSE
  - Disclaimer: disclaimer.md
  - Quick Start:
      - Prerequisites: 0-quickstart/0-prerequisites.md
      - Getting Started: 0-quickstart/1-getting-started.md
  - Architecture:
      - System Overview: 1-architecture/0-overview.md
  - MyProject: # This becomes the main docs for whatever you are building
      - uv Package Manager: 2-project/uv-notes.md
      - Project Topic 1: 2-project/0-topic1.md
      - Project Topic 2: 2-project/1-topic2.md
      - Project Topic 3: 2-project/2-topic3.md
      # etc.
  - Tasks:
      - Tasks: 2-project/tasks/0-overview.md
      - Main Taskfile: 2-project/tasks/1-main-taskfile.md
      - Gitflow Taskfile: 2-project/tasks/2-gitflow-taskfile.md
      # etc.
  - Troubleshooting:
      - Troubleshooting: 3-troubleshooting/0-overview.md
      - Problem 1: 3-troubleshooting/1-problem1.md
      - Problem 2: 3-troubleshooting/2-problem2.md
      # etc.
  - About Me:
      - About Me: 4-about/0-about.md
